import { GoogleGenAI, Modality } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const generateTidyRoomImage = async (
  imageBase64: string,
  mimeType: string
): Promise<string> => {
    const imagePart = {
        inlineData: {
          data: imageBase64,
          mimeType,
        },
    };

    const prompt = `Based on the uploaded image of a room, generate a new image showing the same room but clean, tidy, and well-organized. Maintain the original room's style and essential furniture, but remove all clutter and arrange items neatly.`;

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: { parts: [imagePart, { text: prompt }] },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }
    
    throw new Error("No image was generated by the model.");
};
